### ISSUE TITLE
1.21 not working

### ISSUE THREAD

**Issue by codyisreallycool** [Stonley890/Compass-Tracker#5]
All commands don't work on 1.21

**Comment by Stonley890** [comment]
Released version 1.2.3 for Minecraft 1.21 and 1.21.1.
https://github.com/Stonley890/Compass-Tracker/releases/tag/1.2.3

**Comment by codyisreallycool** [comment]
> Released version 1.2.3 for Minecraft 1.21 and 1.21.1.
> https://github.com/Stonley890/Compass-Tracker/releases/tag/1.2.3

Thank you!
